SOURCE_TYPE_SYSTEM = "system"
SOURCE_TYPE_USER_UPLOAD = "user_upload"

VISIBILITY_GLOBAL = "global"
VISIBILITY_PRIVATE = "private"

DOCUMENT_STATUS_UPLOADED = "uploaded"
DOCUMENT_STATUS_PROCESSING = "processing"
DOCUMENT_STATUS_READY = "ready"
DOCUMENT_STATUS_FAILED = "failed"
DOCUMENT_STATUS_DELETED = "deleted"

SESSION_STATUS_ACTIVE = "active"
SESSION_STATUS_ARCHIVED = "archived"
SESSION_STATUS_DELETED = "deleted"

USER_ROLE_USER = "user"
USER_ROLE_ADMIN = "admin"

CHUNK_TYPE_TEXT = "text"
CHUNK_TYPE_TABLE = "table"
CHUNK_TYPE_IMAGE = "image"
CHUNK_TYPE_MIXED = "mixed"

RETRIEVAL_SCOPE_CURRENT_UPLOAD = "current_upload"
RETRIEVAL_SCOPE_ALL_USER_UPLOADS = "all_user_uploads"
RETRIEVAL_SCOPE_SYSTEM_DOCS = "system_docs"
RETRIEVAL_SCOPE_MIXED = "mixed"
RETRIEVAL_SCOPE_AUTO = "auto"
